#!/bin/zsh

token=$1
resource=$2

url=https://api.ciscospark.com/v1/${resource}

#curl -v $url/$resource -H "Authorization: Bearer ${token}" | jq .items

#while (( ${+url} )); do
while [[ -n "$url" ]]; do

#curl -I does a HEAD http request, so we should't put too much burden on the server
url=$(curl -s -I ${url} -H "Authorization: Bearer ${token}" | awk '/Link: </ { print $2}' | sed -e s/\<//g -e s/\>\;//g)
 
done



