#!/bin/zsh

token=$1
resource=$2

urlarr=()
url=https://api.ciscospark.com/v1/${resource}

while [[ -n "$url" ]]; do
urlarr+=${url}
url=$(curl -s -I ${url} -H "Authorization: Bearer ${token}" | awk '/Link: </ { print $2}' | sed -e s/\<//g -e s/\>\;//g)
done

for val in ${urlarr[@]}; do 
  #now we are equipped to retireve all the values
  curl -s -H "Authorization: Bearer ${token}" ${val} | jq . 
done


